### ISSUE TITLE
WebGUI shutdown triggers reboot

### ISSUE THREAD

**Issue by A380Coding** [Geektoolkit/Dynaframe3#102]
Hitting the shutdown button in the webGUI actually triggeres a reboot command: http://IP:8000/default.htm?COMMAND=REBOOT

Guess it is a copy&paste issue. Reboot and shutdown button both have the reboot command.

Version 2.18

Edit: Just saw the version number on GUI reads 2.17, but I'm sure I updated to 2.18

**Comment by Geektoolkit** [comment]
Ah yeah, the 2.18 version number was a miss on my part, I may in place update for that. Good catch on the reboot/shutdown, I'll work to get those updated

**Comment by RichN001** [comment]
ah nope that one is on me haha... the link on the WebUI Shutdown button is not correct.

**Comment by Geektoolkit** [comment]
Sigh. I'd fire you if i paid you. j/k, you're awesome. I should fire me :D  Ok we can get that in for the next update.

**Comment by Geektoolkit** [comment]
Ok no worries we can get that in for the next update, along with my boneheaded version update to 2.19

**Comment by RichN001** [comment]
def the link for shutdown is reboot, but on the frame im testing on /default.htm?COMMAND=SHUTDOWN is not working.. might have to dig to find that make sure the command is ok. Ill take a look later.

**Comment by Geektoolkit** [comment]
I believe it takes a minute (I execute a 'shutdown' vs. a 'shutdown now'.  I'll change it to 'shutdown now' though. i think I had it that way to allow for windows/linux cross platform support, but I'm ok dropping windows support for now unless there's a huge demand for it.

**Comment by Geektoolkit** [comment]
This is fixed in 2.19 (and better...it does an immediate shutdown). Please reopen if you see it regress. Gui is also fixed to say 2.19
