### ISSUE TITLE
2.19, does not start until

### ISSUE THREAD

**Issue by Archonw** [Geektoolkit/Dynaframe3#107]
Hi,
i started testing 2.19. At first try it didn't start up right after the update process. I need to remove all of the old dynaframe stuff.
Now it starts normal, and i think it works as aspected.

**Comment by Geektoolkit** [comment]
when you say 'didn't startup right' was it the webUI looking all goofed up? or did it not start running the slideshow?  Asking because I saw one issue with the website being goofed up, but am trying to find out if there are more.

**Comment by Archonw** [comment]
It was the slideshow.

**Comment by Geektoolkit** [comment]
Ok that's wierd. I'll keep an eye out for it when I get to 2.20. Thanks for the report, will leave this open in case others hit it.

**Comment by qwksilver** [comment]
i'm encountering this on one unit based on pi3b  and not on my other unit based on pi4

**Comment by qwksilver** [comment]
resolved, or not repeatable, on 2.2 +
