### ISSUE TITLE
How to install it on a normal ubuntu desktop machine ?

### ISSUE THREAD

**Issue by dibyadip-das** [Geektoolkit/Dynaframe3#109]
I am using my old laptop to use it as a DIY Photo frame and was curious about running Dynaframe in a Ubuntu desktop install.

**Comment by Geektoolkit** [comment]
Currently you'd have to compile it for x86. The releases I make are targeted at ARM. But if you compile it should be good to go. Next official release I'll include an x86 version as it shouldn't be much more work. Probably a few weeks out for that currently

**Comment by dibyadip-das** [comment]
Thank you so much @Geektoolkit. Would really love to see my Dynaframe come alive with this release.

**Comment by qwksilver** [comment]
Closing answered issue
