### ISSUE TITLE
v2.04 web ui

### ISSUE THREAD

**Issue by Archonw** [Geektoolkit/Dynaframe3#12]
One idea for the web ui. 
Two different pages. One for the playlist and one for the settings.

**Comment by Geektoolkit** [comment]
I like that. we took a ui revision from tmckay1 that cleans things up a bit, but I do need to thinka bout settings vs. playlists. I'll leave this open so I can think on it and see what I can do.

**Comment by qwksilver** [comment]
this can likely be closed as it's referenced from #16 now

**Comment by Geektoolkit** [comment]
very well we'll track in 16
