### ISSUE TITLE
Documentation :: Change Request - "I believe it's under advanced"

### ISSUE THREAD

**Issue by dankinchen** [Geektoolkit/Dynaframe3#128]
Under the things to clean up section;

**Currently Reads**

- To prevent screen blanking, please run: sudo raspi-config, and then turn off screen blanking in the menus there (I believe it's under advanced) I'm working on getting these into the setup scripts.

**Should Read**

- To prevent screen blanking, please run: sudo raspi-config, and then turn off screen blanking in the menus there under **Display Options** I'm working on getting these into the setup scripts.

**Comment by Geektoolkit** [comment]
Thankyou updated!
