### ISSUE TITLE
Control Panel :: Bug - Version Number is wrong in v2.23

### ISSUE THREAD

**Issue by dankinchen** [Geektoolkit/Dynaframe3#129]
In the web template the version number is showing "2.22.0.0" in the html title tag and on the right of the branding bar  when I installed v2.23.

I would suggest checking the global variable for version number.

**Comment by Geektoolkit** [comment]
Yes good catch. the versions are pulled from the file versions...one is an assembly version and one is the project version. Keeping them in sync can be tricky. I'll work to get that sorted.

**Comment by Geektoolkit** [comment]
Closing because going back to 2.23 to fix this isn't going to be feasable, though I'm heads down on the next release which should fix this.
