### ISSUE TITLE
BUG: Duplicate Directories

### ISSUE THREAD

**Issue by qwksilver** [Geektoolkit/Dynaframe3#15]
somehow i've managed to add pictures three times and get the whole list thrice.
I think it's from using an existing link with the down arrow button to access the webui

![Capture](https://user-images.githubusercontent.com/20508309/94641693-f05b9c00-02af-11eb-9e95-3f6fd67dc12a.JPG)

**Comment by Geektoolkit** [comment]
I see this too, I think I got this squashed in the next update. I'm adding 'distinct()' to the method calls, we'll see if that squashes this one

**Comment by qwksilver** [comment]
i did a few things to recreate this problem in 2.05 and it seems solved.  closing this out as done.
