### ISSUE TITLE
Ignore Slideshow duration between slides for videos

### ISSUE THREAD

**Issue by vatsake** [Geektoolkit/Dynaframe3#167]
Is there a way to ignore "Slideshow duration between slides" for videos?

**Comment by Geektoolkit** [comment]
2.23 has an option for it, but isn't stable.  in 2.19 the latest stable, there isn't currently. I'm working on a release to have this feature in the DynaframePro fork I'm working on, but I also am working on moving off of OMXPlayer, so much work is needed.
Is the scenario a slideshow of say 30 seconds with a longer video that you want to play fully?

**Comment by vatsake** [comment]
Yeah, my video is like 2 minutes long and slideshow transition is 30 seconds.

**Comment by vatsake** [comment]
I'll use 2.23, ty.
