### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by xonacs** [Geektoolkit/Dynaframe3#176]
Hi

are there plans to make this available on linux? One of the cheapest ways of running a digital photo frame is to convert and old laptop.. for this Linux works best I believe ..

**Comment by Geektoolkit** [comment]
This is actually already designed for Linux.  And price wise..the images are designed for raspberry pis. 

That said:
The source code is using .net core and is compatable with linux, macos, and windows. The UI framework is Avalonia which is also cross platform. The builds are raspberry pi which runs a distro based on Debian.  And if someone wants to make a build that is not specific to Debian/Raspberry pi the source is there to adjust/compile for custom builds.
