### ISSUE TITLE
Showing a picture even though it was deleted

### ISSUE THREAD

**Issue by SpaceFahad** [Geektoolkit/Dynaframe3#203]
I have an issue with my Dyna frame showing a picture I already deleted from the folders, I tried everything. However, it still shows it even though I made sure it was deleted and I emptied the web/upload + pictures, then uploaded new ones, new ones show alongside the deleted one.

**Comment by SpaceFahad** [comment]
> not sure what would do this, have you restarted the unit and have the problem still happening?

I have tried restarting, shutting down for a few minutes, and updating the pi, but none worked. The problem still persists.

**Comment by qwksilver** [comment]
i can't replicate this issue, chances are a permissions item has prevented full deletion of the file, as this version is almost 2 years out of active dev now, i would urge you to come check out the patreon edition DynaframePro, it's lightyears ahead of this point, and likely this problem will vanish with the newest image.

**Comment by SpaceFahad** [comment]
> i can't replicate this issue, chances are a permissions item has prevented full deletion of the file, as this version is almost 2 years out of active dev now, i would urge you to come check out the patreon edition DynaframePro, it's lightyears ahead of this point, and likely this problem will vanish with the newest image.

Issue was identified, for some reason a photo I deleted earlier did not get deleted, but instead it was renamed to " .jpg" and was hidden.. I had to show hidden files in WinSCP to be able to find and delete it. 

As for the DFpro, will check it out, thank you!
