### ISSUE TITLE
Option to play videos for their original duration or for the slide duration [enhancement]

### ISSUE THREAD

**Issue by lagnajeet** [Geektoolkit/Dynaframe3#204]
Currently DF plays vides for the same duration as the slide durations. This works well for looped animations or short videos but it would be nice to have an option where DF gets the duration of the video file and plays it for that duration ignoring the slide duration and when it's showing a still picture it goes back to the slide duration.

**Comment by qwksilver** [comment]
This option is available in [DynaframePro Patreon](https://www.patreon.com/Geektoolkit).  This version of dynaframe is end of life for it's devs, community work on improving this old project is still welcome, and encouraged.
