### ISSUE TITLE
Unable to play video

### ISSUE THREAD

**Issue by mengelsen** [Geektoolkit/Dynaframe3#209]
Has this project been abandoned? I'm running Raspbian GNU/Linux 11 (bullseye) and I find myself unable to play video files using Dynaframe. 

Here is the error message that I'm getting:
`[omxplayer not working: error while loading shared libraries: libbrcmEGL.so](https://forums.raspberrypi.com/viewtopic.php?t=323322&sid=82cde12c6f0749ad92f000a854c3a169)`

According to the Raspberry Pi community, this is because in Bullseye omxplayer is depreciated.
https://forums.raspberrypi.com/viewtopic.php?t=323322#p1953155

I tried following these instructions ☝🏻 but now Dynaframe isn't working at all. I'm getting a `Segmentation fault`.

**Comment by qwksilver** [comment]
The project is not supported on bullseye, but still does pretty good on buster.  This version is at EOL except for being left open for community development.  Event the active version, DynaFramePro is only working on Buster/Linux 10.  The main project has tons of new features and performance tweaks.  It is a patreon project.  You can find that here:  https://www.patreon.com/Geektoolkit
