### ISSUE TITLE
Bug: Startup in 90 deg Portrait

### ISSUE THREAD

**Issue by qwksilver** [Geektoolkit/Dynaframe3#26]
26a, formerly 21h. 90 degree rotation, and uniform, scalling results in screen with 100px border all round the photo, this may not occur in portrait, not sure

video here: https://www.youtube.com/watch?v=hA4UPTsFkV8

images sizes
1: 1080,1920
2: 757x1346
3: 1080.1770

**Comment by Geektoolkit** [comment]
Oh wow that's interesting, the time/text doesn't ever fix either. I'll try to get a repro, probably midweek before I get time on it again. Thanks for the video of the repro!  I've been thinking about how to try to get things more stable on boot and think I have an idea.

**Comment by Geektoolkit** [comment]
I feel like this is resolved with 2.09, please re-open if you're seeing it still. @qwksilver
