### ISSUE TITLE
Screen blanking

### ISSUE THREAD

**Issue by racompton** [Geektoolkit/Dynaframe3#30]
With the default install of Rasberry Pi OS, the lxterminal will blank after a few mins of inactivity.  I had to navigate to Preferences > Raspberry Pi Configuration and click on Display and then select Screen Blanking to Disable.  You may want to include this in your instructions or add in a config that will disable this.

**Comment by Geektoolkit** [comment]
Thankyou, I've added this to the initial instructions in the readme.
