### ISSUE TITLE
Mouse pointer still showing up

### ISSUE THREAD

**Issue by racompton** [Geektoolkit/Dynaframe3#31]
I found that the mouse pointer kept showing up so I did "sudo apt install unclutter" and then executed "unclutter -idle 0"

**Comment by Geektoolkit** [comment]
Thankyou, good bug. I'll have to get this into the startup script after reboot on the next update

**Comment by Geektoolkit** [comment]
I've added this to the readme to run as part of setting up a device. I may add it in the future to the install script, but for now, closing this out as a documented manual step
