### ISSUE TITLE
Feature Request: Restart Dynaframe from Webinterface

### ISSUE THREAD

**Issue by Pixelshading** [Geektoolkit/Dynaframe3#32]
Hello there.

It would be nice to be able to restart Dynaframe from the Webinterface. (Just in case something is messup and you want to restart Dynaframe).

Greets
Pixelshading

**Comment by qwksilver** [comment]
on the list #21 discused at #16 item 6, and original discussed in more detail [#7 comment 3][https://github.com/Geektoolkit/Dynaframe3/issues/7#issuecomment-699647101)

this issue may be closed as a duplicate

**Comment by Geektoolkit** [comment]
Pixelshading, thankyou, this is something I'm working on, hoping to have it in for the next build (along with screen on/off). Closing as a dupe
