### ISSUE TITLE
Bug: Show Time and IP Address shown time wont apply without restart.

### ISSUE THREAD

**Issue by Pixelshading** [Geektoolkit/Dynaframe3#33]
Changing the Show Time Option in the Settings wont apply until you restart Dynaframe or Reboot Raspberry.

This also applys to the Show IP Address Time Setting.

Used Computer: Raspberry Pi 4
Used OS; Raspberry Pi OS (Based on Debian Buster)
Used Dynaframe Version: 2.08

Greets
Pixelshading

**Comment by qwksilver** [comment]
on the list at #21 f

**Comment by qwksilver** [comment]
2.09 resolves these issues
