### ISSUE TITLE
Recommended Specs?

### ISSUE THREAD

**Issue by Cydoemus** [Geektoolkit/Dynaframe3#35]
Looking to setup a wall of digital frames as a Christmas present for the wife. Never used a pi before so I need to know the recommended type to get for this project. I plan on having multiple screens being used so maybe there is a chance of the Pi driving more than one screen at a time? Any help would be appreciated

**Comment by Geektoolkit** [comment]
Hi, I'm excited you're looking to use it!  Dual screens are not currently supported due to issues beyond my control currently (the library I'm building on)

I recommend a pi4 2Gig with a 1080p monitor.  4K monitors aren't supported yet.
