### ISSUE TITLE
2.09 + 2.11 rotating pictures 270 degree doesn't work as intended

### ISSUE THREAD

**Issue by Pixelshading** [Geektoolkit/Dynaframe3#41]
Hello,

selecting the option in the webinterface to rotate the Pictures 270 degree won't put them into "portrait" mode correctly. They get cutoff. Changing the Image Scaling doesn't help either.

This happens only if you select 270 degree rotation, the other options work fine.

happens on Version 2.09 and now tested with 2.11 and it's still there.

Greets
Pixel

**Comment by Geektoolkit** [comment]
Argh. Good bug, got a repro. Fix coming in next build.

**Comment by Geektoolkit** [comment]
This is fixed in 2.12.  Thanks for pointing this out, knowing when it regressed and that it was only 270 degrees helped me narrow it down and fix it quickly.
