### ISSUE TITLE
Documentation: Exit/Close

### ISSUE THREAD

**Issue by qwksilver** [Geektoolkit/Dynaframe3#6]
I found a way to exit to desktop (ESC) to adjust rclone, and screen saver settings, however as a user of pi/linix with almost no experience, I tried Ctrl-C, Ctr-X, and a few other combos a lot, and only thought of esc after about 1/2 hour.  total face palm moment, but i was reading through the documentation and no mention of how to stop was shown.

as an aside to that, restarting without rebooting

**Comment by Geektoolkit** [comment]
Thanks this is good feedback, I've updated the wiki and the readme with this info.

To restart, simply launch Dynaframe form the pi\Dynaframe folder.  I'll work to make it easier to figure out.

**Comment by qwksilver** [comment]
suggest add launch shortcut to taskbar and menu
