### ISSUE TITLE
COMMAND=INFOBAR_IP

### ISSUE THREAD

**Issue by RichN001** [Geektoolkit/Dynaframe3#74]
Seems like the for COMMAND=INFOBAR_IP does not work. However on a keyboard pressing the "I" Key does work. Looses it somewhere for the command. Havent looked in to it, just wanted to get it logged.

**Comment by Geektoolkit** [comment]
Thanks for logging it, I'll add it to my todo list when I get back into the code.

**Comment by RichN001** [comment]
hey no problem. I have a huge PR for you, wont be ready for another day or so. I've resolved this...

**Comment by qwksilver** [comment]
2.16 fixes this issue, thanks to RichN001
