### ISSUE TITLE
The naming convention of this app is a bit strange... Dynaframe 3  but files are Dynaframe2 ?

### ISSUE THREAD

**Issue by Spinner65** [Geektoolkit/Dynaframe3#87]
Based on the Geektoolkit youtube videos, I understand that the 2nd generation of Dynaframe was never really released, but the naming of files etc is slightly confusing.

For example:
-current Dynaframe 3 download file is called "Dynaframe2.zip"  not Dynaframe3.zip  or Dynaframe3v2.xx.zip
-comment section of the install/upgrade shell script has "Geektoolkit present: Dynaframe 2.0"

**Comment by Geektoolkit** [comment]
Yeah, this was a screwup I made when creating the project, and it's in a goofy state for now.  My plan is to advance it to the stage where it truly deserves to be "Dynaframe 3" (which is, btw, totally an arbitrary decsion I'll make one day) and then I'll rename the files/releases/etc. to match the github repo and this will all be Dynafframe3.

I'd like to get it to the point where if I put the software on a frame and gave it to someone, they could set it up, connect to wifi, use their phone to control it, add images, and it's stable and works.  That's my current idea for when I'll up the nubmering to 3 and fix this mess I created :)
